- name: Install memcached server
  apt: pkg=memcached state=installed update-cache=yes

- name: Install header files
  apt: pkg=libmemcached-dev  state=installed update-cache=yes

- name: Install configuration file
  template: src=memcached.conf.j2 dest=/etc/memcached.conf
  notify: restart memcached
