- name: Create uwsgi log folder
  file: path={{ uwsgi_log_folder }} state=directory

- name: Ensure uwsgi is at the desired version
  apt: pkg=uwsgi state=latest

- name: Ensure Python uwsgi plugin is installed
  apt: pkg=uwsgi-plugin-python

- name: Ensure runs with the latest uwsgi configuration file
  template: src={{ uwsgi_conf_file }} dest=/etc/uwsgi/apps-available/web_ide.ini
  notify:
    - restart uwsgi

- name: Enable web_ide app
  file: src=/etc/uwsgi/apps-available/web_ide.ini dest=/etc/uwsgi/apps-enabled/web_ide.ini state=link
  notify:
    - restart uwsgi
