- name: update apt cache
  apt: update_cache=yes

- name: install python development files
  apt: name=python-dev state=present

- name: install pip
  apt: name=python-pip state=present

- name: install git
  apt: name=git state=present

- name: install libpq-dev
  apt: name=libpq-dev state=present

- name: install virtualenv
  pip: name=virtualenv

- name: create virtualenv
  command: virtualenv {{ virtualenv_path }}

- name: install app requirements
  pip: requirements={{ requirements_file_path }} virtualenv={{ virtualenv_path }} extra_args='--upgrade setuptools'

- name: create log folder
  file: path={{ log_folder }} state=directory